
name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  DockerBuild:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: gitclone 
        run: git clone https://github.com/sudhakarann33/gha.git
      - name: docker installation 
        run: curl -fsSL https://get.docker.com | sh 
      - name: docker login 
        run: docker login -u ${{secrets.DOCKERHUBUSERNAME}} -p ${{secrets.DOCKERHUBPASSWORD}}
      - name: docker build 
        run: cd gha && docker build . -t fast_api:sudhakar
      - name: test
        run: echo "hello"
      - name: docker tag & push  
        run: docker tag fast_api:sudhakar shubhambawa98/testlkm:satyam && docker push shubhambawa98/testlkm:sudhakar
        
      - name: login Target Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 40.71.56.99
          username: dockerpoc
          password: ${{ secrets.SERVERPASSWORD }}
          port: 22
          script: | 
             sudo docker login -u ${{secrets.DOCKERHUBUSERNAME}} -p ${{secrets.DOCKERHUBPASSWORD}}
             sudo docker pull shubhambawa98/testlkm:latest
             sudo docker run -d -P shubhambawa98/testlkm:latest
